-- migration: 20260710231450_directories
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

CREATE TABLE directories (
    path        TEXT PRIMARY KEY,
    path_lower  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);
CREATE UNIQUE INDEX idx_directories_path_lower ON directories (path_lower);
