-- migration: 20260710232630_upload_queue
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

CREATE TABLE upload_queue (
    path            TEXT PRIMARY KEY,
    op              TEXT NOT NULL,
    dest            TEXT,
    origin          TEXT,
    enqueued_at     TEXT NOT NULL,
    attempts        INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TEXT NOT NULL,
    state           TEXT NOT NULL DEFAULT 'pending',
    last_error      TEXT
);
CREATE INDEX idx_upload_queue_due ON upload_queue (state, next_attempt_at);

-- TODO: write the forward-only schema change below.
