-- migration: 20260711022001_add_identities
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

CREATE TABLE identities (
    id         TEXT PRIMARY KEY,
    iss        TEXT NOT NULL,
    sub        TEXT NOT NULL,
    email      TEXT NOT NULL,
    name       TEXT,
    picture    TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (iss, sub)
);
