-- migration: 20260711022834_add_owner_id_to_auth_artifacts
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

ALTER TABLE web_sessions ADD COLUMN owner_id TEXT;
ALTER TABLE oauth_authcodes ADD COLUMN owner_id TEXT;
ALTER TABLE oauth_chains ADD COLUMN owner_id TEXT;
ALTER TABLE personal_tokens ADD COLUMN owner_id TEXT;
