-- migration: 20260711182447_add_oauth_state_return_to
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

-- TODO: write the forward-only schema change below.
-- Preserve the same-site destination selected when a web login starts. NULL
-- continues to represent handshakes created before this optional field existed.
ALTER TABLE oauth_state ADD COLUMN return_to TEXT NULL;
