// Package opsctl is the on-box platform CLI's core: the install / rollback /
// prune verbs over the versioned libexec binary + atomic bin/run symlink layout.
//
// EVERY filesystem operation is rooted at a configurable base (OPSCTL_ROOT,
// default /opt) so the whole package is testable against a temp dir with no real
// box. The box-only bits — systemd restart / is-active, and subprocess
// invocation of the app binary's fixed verbs (version|manifest|migrate|schema|
// backup|restore) — sit behind the System and AppRunner seams the tests stub.
package opsctl

import (
	"os"
	"path/filepath"
)

// Layout resolves the on-box paths for one app under a configurable root. The
// real box uses root="/opt"; tests use a temp dir. The stable paths bin/run and
// etc/manifest.env and the never-touched state/<app>.db are computed here so
// every verb shares one definition.
//
// SysRoot is the parallel base for the box's SYSTEM-config tree (/etc/systemd,
// /etc/nginx, /var/lib/letsencrypt). install/rollback/prune never touch it; the
// D1 verbs init-box/setup write their config artifacts there (under SysRoot so a
// test can byte-assert them against a temp dir). The box uses SysRoot="/"; tests
// point it at a temp dir. Empty ⇒ "/".
type Layout struct {
	Root    string // OPSCTL_ROOT, default "/opt" — the /opt/<app> tree
	SysRoot string // system-config base, default "/" — the /etc + /var tree
	App     string // service name
}

// NewLayout builds the layout for app under root (root="" ⇒ "/opt"), with the
// system-config base defaulting to "/". Use NewLayoutSys to override SysRoot.
func NewLayout(root, app string) Layout {
	return NewLayoutSys(root, "", app)
}

// NewLayoutSys builds the layout for app under root (""⇒"/opt") and sysRoot
// (""⇒"/"). Tests pass a temp dir for both so init-box/setup write their config
// artifacts where the test can read them.
func NewLayoutSys(root, sysRoot, app string) Layout {
	if root == "" {
		root = "/opt"
	}
	if sysRoot == "" {
		sysRoot = "/"
	}
	return Layout{Root: root, SysRoot: sysRoot, App: app}
}

// AppDir is /opt/<app> — the per-app install root.
func (l Layout) AppDir() string { return filepath.Join(l.Root, l.App) }

func (l Layout) stageScratchParent() string { return l.Root }

// ReleaseLibexecFile is kept as the compareVersion tie-breaker path for existing
// callers; under the current layout it is the shipped libexec binary itself.
func (l Layout) ReleaseLibexecFile(version string) string {
	return l.LibexecBinary(version)
}

// BinDir is /opt/<app>/bin.
func (l Layout) BinDir() string { return filepath.Join(l.AppDir(), "bin") }

// RunLink is /opt/<app>/bin/run — the STABLE path ikigenba-launch execs. Deploy
// and rollback atomically repoint it at a complete libexec/<app>-<version>
// binary, so the launcher sees either the old binary or the new binary.
func (l Layout) RunLink() string { return filepath.Join(l.BinDir(), "run") }

// RunTarget returns the live bin/run target if it exists; before first deploy it
// returns the unversioned libexec basename as a deterministic default.
func (l Layout) RunTarget() string {
	if dst, err := os.Readlink(l.RunLink()); err == nil {
		return dst
	}
	return filepath.Join("..", "libexec", l.App)
}

func (l Layout) runTarget(version string) string {
	return filepath.Join("..", "libexec", l.App+"-"+version)
}

// EtcDir is /opt/<app>/etc.
func (l Layout) EtcDir() string { return filepath.Join(l.AppDir(), "etc") }

// EtcVersionDir is /opt/<app>/etc/<version> — the retained per-version config
// home selected by the etc/current symlink.
func (l Layout) EtcVersionDir(version string) string {
	return filepath.Join(l.EtcDir(), version)
}

// NginxConfFile is /opt/<app>/etc/<version>/nginx.conf.
func (l Layout) NginxConfFile(version string) string {
	return filepath.Join(l.EtcVersionDir(version), "nginx.conf")
}

// ManifestFile is /opt/<app>/etc/<version>/manifest.env.
func (l Layout) ManifestFile(version string) string {
	return filepath.Join(l.EtcVersionDir(version), "manifest.env")
}

// EtcCurrentLink is /opt/<app>/etc/current — the active config symlink.
func (l Layout) EtcCurrentLink() string { return filepath.Join(l.EtcDir(), "current") }

// ActiveNginxConf is /opt/<app>/etc/current/nginx.conf.
func (l Layout) ActiveNginxConf() string {
	return filepath.Join(l.EtcCurrentLink(), "nginx.conf")
}

// ActiveManifest is /opt/<app>/etc/current/manifest.env.
func (l Layout) ActiveManifest() string {
	return filepath.Join(l.EtcCurrentLink(), "manifest.env")
}

// ManifestPath is /opt/<app>/etc/manifest.env — the STABLE path the dashboard's
// resource derivation and bin/registry read; regenerated by `<app> manifest` on
// every swap (PLAN §2.6).
func (l Layout) ManifestPath() string { return filepath.Join(l.EtcDir(), "manifest.env") }

func (l Layout) shareDir() string { return filepath.Join(l.AppDir(), "share") }

// ShareVersionDir is /opt/<app>/share/<version> — the retained per-version
// static asset home selected by the share/current symlink.
func (l Layout) ShareVersionDir(version string) string {
	return filepath.Join(l.shareDir(), version)
}

// ShareCurrentLink is /opt/<app>/share/current — the active static asset symlink.
func (l Layout) ShareCurrentLink() string { return filepath.Join(l.shareDir(), "current") }

// LibexecDir is /opt/<app>/libexec — where shipped service binaries land.
func (l Layout) LibexecDir() string { return filepath.Join(l.AppDir(), "libexec") }

// LibexecBinary is /opt/<app>/libexec/<app>-<version> — one shipped service binary.
func (l Layout) LibexecBinary(version string) string {
	return filepath.Join(l.LibexecDir(), l.App+"-"+version)
}

// StateDir is /opt/<app>/state.
func (l Layout) StateDir() string { return filepath.Join(l.AppDir(), "state") }

// DBPath is /opt/<app>/state/<app>.db — state, NEVER touched on deploy except the
// explicit pre-migration backup copy.
func (l Layout) DBPath() string { return filepath.Join(l.StateDir(), l.App+".db") }

// CacheDir is /opt/<app>/cache.
func (l Layout) CacheDir() string { return filepath.Join(l.AppDir(), "cache") }

// GenerationPath is /opt/<app>/cache/<app>.db.generation.
func (l Layout) GenerationPath() string {
	_ = os.MkdirAll(l.CacheDir(), 0o755)
	return filepath.Join(l.CacheDir(), l.App+".db.generation")
}

// WWWDir is /opt/<app>/state/www — the SEPARATE world-readable static tree the sites
// service serves from (default SITES_ROOT). Unlike state/ (0750), this whole
// subtree is 0755 owned by <app>:<app> so nginx (www-data) can traverse+read it.
// Only apps that opt in (sites) get this tree; setup creates none otherwise.
func (l Layout) WWWDir() string { return filepath.Join(l.StateDir(), "www") }

func (l Layout) WWWRoot() string { return l.WWWDir() }

// WWWWorkingDir is /opt/<app>/state/www/working — draft site trees authored via MCP.
func (l Layout) WWWWorkingDir() string { return filepath.Join(l.WWWRoot(), "working") }

// WWWPublicDir is /opt/<app>/state/www/public — publish symlinks → working trees.
func (l Layout) WWWPublicDir() string {
	return filepath.Join(l.WWWDir(), "public")
}

// WWWPrivateDir is /opt/<app>/state/www/private — the private served surface.
func (l Layout) WWWPrivateDir() string {
	return filepath.Join(l.WWWDir(), "private")
}

// BackupsDir is /opt/<app>/backups — where install drops the pre-migration DB
// snapshot keyed by the FROM-version, so the matching rollback can restore it.
func (l Layout) BackupsDir() string { return filepath.Join(l.AppDir(), "backups") }

// PreMigrationBackup is the snapshot install takes before a schema-advancing
// migrate, named by the version being installed (the rollback target restores the
// snapshot whose name matches the release it is rolling back FROM).
func (l Layout) PreMigrationBackup(version string) string {
	return filepath.Join(l.BackupsDir(), "pre-"+version+".db")
}

// ---- System-config paths (rooted at SysRoot; written by init-box / setup) ----

// SystemdDir is <SysRoot>/etc/systemd/system — where unit files land.
func (l Layout) SystemdDir() string {
	return filepath.Join(l.SysRoot, "etc", "systemd", "system")
}

// UnitPath is <SysRoot>/etc/systemd/system/<app>.service — the per-app unit
// setup writes (ExecStart=/usr/local/bin/ikigenba-launch <app>, enabled not
// started), byte-matching today's bin/setup heredoc.
func (l Layout) UnitPath() string {
	return filepath.Join(l.SystemdDir(), l.App+".service")
}

// RenewTimerPath / RenewServicePath are the certbot renewal timer+service
// init-box writes (the apex cert renewal). A self-contained
// ikigenba-certbot-renew.{timer,service} pair, so the byte content is asserted
// in tests rather than depending on a package-provided timer.
func (l Layout) RenewTimerPath() string {
	return filepath.Join(l.SystemdDir(), "ikigenba-certbot-renew.timer")
}

func (l Layout) RenewServicePath() string {
	return filepath.Join(l.SystemdDir(), "ikigenba-certbot-renew.service")
}

// BackupTimerPath / BackupServicePath are the suite-owned nightly box sweep
// timer+service. The service runs `opsctl backup --all`; the timer owns the
// deterministic 03:00 America/Chicago cadence.
func (l Layout) BackupTimerPath() string {
	return filepath.Join(l.SystemdDir(), "ikigenba-backup.timer")
}

func (l Layout) BackupServicePath() string {
	return filepath.Join(l.SystemdDir(), "ikigenba-backup.service")
}

// NginxConfDir is <SysRoot>/etc/nginx/conf.d — where the apex server block lands.
func (l Layout) NginxConfDir() string {
	return filepath.Join(l.SysRoot, "etc", "nginx", "conf.d")
}

// ApexBlockPath is <SysRoot>/etc/nginx/conf.d/<app>.conf — the apex server{}
// block for the DEFAULT app (today dashboard/bin/setup writes /etc/nginx/conf.d/
// dashboard.conf). init-box owns it; the app name is the DEFAULT app's name.
func (l Layout) ApexBlockPath() string {
	return filepath.Join(l.NginxConfDir(), l.App+".conf")
}

// LocationsDir is <SysRoot>/etc/nginx/conf.d/locations — the include dir the
// per-app fragments drop into. init-box creates it; setup writes into it.
func (l Layout) LocationsDir() string {
	return filepath.Join(l.NginxConfDir(), "locations")
}

// FragmentPath is <SysRoot>/etc/nginx/conf.d/locations/<app>.conf — the per-app
// location fragment setup drops, byte-matching today's bin/setup output.
func (l Layout) FragmentPath() string {
	return filepath.Join(l.LocationsDir(), l.App+".conf")
}

// LetsEncryptWebroot is <SysRoot>/var/lib/letsencrypt — the HTTP-01 webroot
// init-box provisions for certbot.
func (l Layout) LetsEncryptWebroot() string {
	return filepath.Join(l.SysRoot, "var", "lib", "letsencrypt")
}
