// Package opsctl is the on-box platform CLI's core: the install / rollback /
// prune verbs over the versioned release-dir + atomic-symlink layout (PLAN §1.4,
// ADR "opsctl — per-verb internals").
//
// EVERY filesystem operation is rooted at a configurable base (OPSCTL_ROOT,
// default /opt) so the whole package is testable against a temp dir with no real
// box. The box-only bits — systemd restart / is-active, and subprocess
// invocation of the app binary's fixed verbs (version|manifest|migrate|schema|
// backup|restore) — sit behind the System and AppRunner seams the tests stub.
package opsctl

import (
	"path/filepath"
)

// Layout resolves the on-box paths for one app under a configurable root. The
// real box uses root="/opt"; tests use a temp dir. The stable paths bin/run and
// etc/manifest.env (PLAN §2.6) and the never-touched data/<app>.db (PLAN §2.7)
// are computed here so every verb shares one definition.
//
// SysRoot is the parallel base for the box's SYSTEM-config tree (/etc/systemd,
// /etc/nginx, /var/lib/letsencrypt). install/rollback/prune never touch it; the
// D1 verbs init-box/setup write their config artifacts there (under SysRoot so a
// test can byte-assert them against a temp dir). The box uses SysRoot="/"; tests
// point it at a temp dir. Empty ⇒ "/".
type Layout struct {
	Root    string // OPSCTL_ROOT, default "/opt" — the /opt/<app> tree
	SysRoot string // system-config base, default "/" — the /etc + /var tree
	App     string // service name
}

// NewLayout builds the layout for app under root (root="" ⇒ "/opt"), with the
// system-config base defaulting to "/". Use NewLayoutSys to override SysRoot.
func NewLayout(root, app string) Layout {
	return NewLayoutSys(root, "", app)
}

// NewLayoutSys builds the layout for app under root (""⇒"/opt") and sysRoot
// (""⇒"/"). Tests pass a temp dir for both so init-box/setup write their config
// artifacts where the test can read them.
func NewLayoutSys(root, sysRoot, app string) Layout {
	if root == "" {
		root = "/opt"
	}
	if sysRoot == "" {
		sysRoot = "/"
	}
	return Layout{Root: root, SysRoot: sysRoot, App: app}
}

// AppDir is /opt/<app> — the per-app install root.
func (l Layout) AppDir() string { return filepath.Join(l.Root, l.App) }

// ReleasesDir is /opt/<app>/releases — the parent of every versioned release.
func (l Layout) ReleasesDir() string { return filepath.Join(l.AppDir(), "releases") }

// ReleaseDir is /opt/<app>/releases/<version> — one version's directory.
func (l Layout) ReleaseDir(version string) string {
	return filepath.Join(l.ReleasesDir(), version)
}

// ReleaseBinary is /opt/<app>/releases/<version>/<app> — the binary for a version.
func (l Layout) ReleaseBinary(version string) string {
	return filepath.Join(l.ReleaseDir(version), l.App)
}

// ReleaseLibexecFile is /opt/<app>/releases/<version>/libexec/<app>: the
// per-build file whose mtime breaks ties between SemVer-precedence-equal builds.
func (l Layout) ReleaseLibexecFile(version string) string {
	return filepath.Join(l.ReleaseDir(version), "libexec", l.App)
}

// CurrentLink is /opt/<app>/current — the symlink swapped atomically to point at
// the live release dir (ln -sfn semantics).
func (l Layout) CurrentLink() string { return filepath.Join(l.AppDir(), "current") }

// CurrentBinary is /opt/<app>/current/<app> — the binary reached through current.
func (l Layout) CurrentBinary() string { return filepath.Join(l.CurrentLink(), l.App) }

// BinDir is /opt/<app>/bin.
func (l Layout) BinDir() string { return filepath.Join(l.AppDir(), "bin") }

// RunLink is /opt/<app>/bin/run — the STABLE path ikigenba-launch execs. A
// symlink to ../current/<app>; set once and never repointed (the cutover happens
// at CurrentLink), so it stays valid mid-swap (PLAN §2.6).
func (l Layout) RunLink() string { return filepath.Join(l.BinDir(), "run") }

// RunTarget is the relative target bin/run points at: ../current/<app>. Relative
// so the symlink survives a box-path move and resolves through CurrentLink.
func (l Layout) RunTarget() string {
	return filepath.Join("..", "current", l.App)
}

// EtcDir is /opt/<app>/etc.
func (l Layout) EtcDir() string { return filepath.Join(l.AppDir(), "etc") }

// ManifestPath is /opt/<app>/etc/manifest.env — the STABLE path the dashboard's
// resource derivation and bin/registry read; regenerated by `<app> manifest` on
// every swap (PLAN §2.6).
func (l Layout) ManifestPath() string { return filepath.Join(l.EtcDir(), "manifest.env") }

// DataDir is /opt/<app>/data.
func (l Layout) DataDir() string { return filepath.Join(l.AppDir(), "data") }

// DBPath is /opt/<app>/data/<app>.db — state, NEVER touched on deploy except the
// explicit pre-migration backup copy (PLAN §2.7).
func (l Layout) DBPath() string { return filepath.Join(l.DataDir(), l.App+".db") }

// GenerationPath is the event-plane epoch sidecar next to the DB.
func (l Layout) GenerationPath() string { return l.DBPath() + ".generation" }

// WWWRoot is /opt/<app>/www — the SEPARATE world-readable static tree the sites
// service serves from (default SITES_ROOT). Unlike data/ (0750), this whole
// subtree is 0755 owned by <app>:<app> so nginx (www-data) can traverse+read it.
// Only apps that opt in (sites) get this tree; setup creates none otherwise.
func (l Layout) WWWRoot() string { return filepath.Join(l.AppDir(), "www") }

// WWWWorkingDir is /opt/<app>/www/working — draft site trees authored via MCP.
func (l Layout) WWWWorkingDir() string { return filepath.Join(l.WWWRoot(), "working") }

// WWWServedDir is /opt/<app>/www/served — the publish surface nginx serves.
func (l Layout) WWWServedDir() string { return filepath.Join(l.WWWRoot(), "served") }

// WWWPublicDir is /opt/<app>/www/served/public — publish symlinks → working trees.
func (l Layout) WWWPublicDir() string { return filepath.Join(l.WWWServedDir(), "public") }

// WWWPrivateDir is /opt/<app>/www/served/private — the private served surface.
func (l Layout) WWWPrivateDir() string { return filepath.Join(l.WWWServedDir(), "private") }

// BackupsDir is /opt/<app>/backups — where install drops the pre-migration DB
// snapshot keyed by the FROM-version, so the matching rollback can restore it.
func (l Layout) BackupsDir() string { return filepath.Join(l.AppDir(), "backups") }

// PreMigrationBackup is the snapshot install takes before a schema-advancing
// migrate, named by the version being installed (the rollback target restores the
// snapshot whose name matches the release it is rolling back FROM).
func (l Layout) PreMigrationBackup(version string) string {
	return filepath.Join(l.BackupsDir(), "pre-"+version+".db")
}

// ---- System-config paths (rooted at SysRoot; written by init-box / setup) ----

// SystemdDir is <SysRoot>/etc/systemd/system — where unit files land.
func (l Layout) SystemdDir() string {
	return filepath.Join(l.SysRoot, "etc", "systemd", "system")
}

// UnitPath is <SysRoot>/etc/systemd/system/<app>.service — the per-app unit
// setup writes (ExecStart=/usr/local/bin/ikigenba-launch <app>, enabled not
// started), byte-matching today's bin/setup heredoc.
func (l Layout) UnitPath() string {
	return filepath.Join(l.SystemdDir(), l.App+".service")
}

// RenewTimerPath / RenewServicePath are the certbot renewal timer+service
// init-box writes (the apex cert renewal). A self-contained
// ikigenba-certbot-renew.{timer,service} pair, so the byte content is asserted
// in tests rather than depending on a package-provided timer.
func (l Layout) RenewTimerPath() string {
	return filepath.Join(l.SystemdDir(), "ikigenba-certbot-renew.timer")
}

func (l Layout) RenewServicePath() string {
	return filepath.Join(l.SystemdDir(), "ikigenba-certbot-renew.service")
}

// NginxConfDir is <SysRoot>/etc/nginx/conf.d — where the apex server block lands.
func (l Layout) NginxConfDir() string {
	return filepath.Join(l.SysRoot, "etc", "nginx", "conf.d")
}

// ApexBlockPath is <SysRoot>/etc/nginx/conf.d/<app>.conf — the apex server{}
// block for the DEFAULT app (today dashboard/bin/setup writes /etc/nginx/conf.d/
// dashboard.conf). init-box owns it; the app name is the DEFAULT app's name.
func (l Layout) ApexBlockPath() string {
	return filepath.Join(l.NginxConfDir(), l.App+".conf")
}

// LocationsDir is <SysRoot>/etc/nginx/conf.d/locations — the include dir the
// per-app fragments drop into. init-box creates it; setup writes into it.
func (l Layout) LocationsDir() string {
	return filepath.Join(l.NginxConfDir(), "locations")
}

// FragmentPath is <SysRoot>/etc/nginx/conf.d/locations/<app>.conf — the per-app
// location fragment setup drops, byte-matching today's bin/setup output.
func (l Layout) FragmentPath() string {
	return filepath.Join(l.LocationsDir(), l.App+".conf")
}

// LetsEncryptWebroot is <SysRoot>/var/lib/letsencrypt — the HTTP-01 webroot
// init-box provisions for certbot.
func (l Layout) LetsEncryptWebroot() string {
	return filepath.Join(l.SysRoot, "var", "lib", "letsencrypt")
}
