-- migration: 20260715173020_verification_schemes
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

ALTER TABLE webhooks ADD COLUMN verification TEXT NOT NULL DEFAULT 'bearer';
ALTER TABLE webhooks ADD COLUMN secret TEXT;
