-- migration: 20260715173925_create_sessions
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

-- TODO: write the forward-only schema change below.
CREATE TABLE sessions (
    id           TEXT PRIMARY KEY,
    repo_name    TEXT NOT NULL,
    owner_email  TEXT NOT NULL,
    issue_number INTEGER,
    attempt      INTEGER NOT NULL,
    branch       TEXT NOT NULL,
    instructions TEXT NOT NULL,
    status       TEXT NOT NULL,
    error        TEXT,
    pr_url       TEXT,
    created_at   TEXT NOT NULL,
    started_at   TEXT,
    ended_at     TEXT,
    log_path     TEXT NOT NULL
);
CREATE INDEX idx_sessions_repo   ON sessions(repo_name, created_at);
CREATE INDEX idx_sessions_status ON sessions(status);
CREATE INDEX idx_sessions_issue  ON sessions(repo_name, issue_number);
