-- migration: 20260715173914_create_repos
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

-- TODO: write the forward-only schema change below.
CREATE TABLE schema_migrations (
    version    INTEGER PRIMARY KEY,
    applied_at TEXT NOT NULL
);

CREATE TABLE repos (
    name           TEXT PRIMARY KEY,
    owner_email    TEXT NOT NULL,
    clone_url      TEXT NOT NULL,
    default_branch TEXT NOT NULL,
    created_at     TEXT NOT NULL
);
