-- migration: 20260708010236_add_public_created_by
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

ALTER TABLE sites ADD COLUMN public INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sites ADD COLUMN created_by TEXT NOT NULL DEFAULT '';
