-- migration: 20260708012637_drop_publish_lifecycle
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

ALTER TABLE sites DROP COLUMN tier;
ALTER TABLE sites DROP COLUMN published;
ALTER TABLE sites DROP COLUMN published_at;
