-- migration: 20260712191337_outbox_kind_subject
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

-- Eventplane's routing envelope now carries a kind and subject rather than a
-- single type. Preserve existing event history by mapping the old type to kind
-- and using the empty root subject, then replace the table atomically.
ALTER TABLE outbox RENAME TO outbox_old;
CREATE TABLE outbox (
  seq        INTEGER PRIMARY KEY AUTOINCREMENT,
  event_id   TEXT    NOT NULL,
  kind       TEXT    NOT NULL,
  subject    TEXT    NOT NULL DEFAULT '',
  payload    TEXT    NOT NULL,
  created_at TEXT    NOT NULL
);
INSERT INTO outbox (seq, event_id, kind, subject, payload, created_at)
SELECT seq, event_id, type, '', payload, created_at FROM outbox_old;
DROP TABLE outbox_old;
CREATE INDEX idx_outbox_created_at ON outbox(created_at);
