-- migration: 20260712184029_external_ref
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

ALTER TABLE transactions ADD COLUMN external_ref TEXT NULL;
CREATE UNIQUE INDEX idx_transactions_external_ref
    ON transactions(external_ref) WHERE external_ref IS NOT NULL;
