-- migration: 20260624002935_subject_merge_jobs
-- Generated by bin/new-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.
-- See docs/adr-migration-timestamps.md.

CREATE TABLE subject_merges (
    job_id          TEXT PRIMARY KEY REFERENCES jobs(id) ON DELETE CASCADE,
    from_subject_id TEXT NOT NULL,
    to_subject_id   TEXT NOT NULL,
    CHECK (from_subject_id <> to_subject_id)
);

CREATE INDEX subject_merges_from_to ON subject_merges (from_subject_id, to_subject_id);

CREATE TRIGGER subjects_restrict_claims_before_delete
BEFORE DELETE ON subjects
WHEN EXISTS (SELECT 1 FROM claims WHERE subject_id = OLD.id)
BEGIN
    SELECT RAISE(ABORT, 'subject has claims');
END;
