-- migration: 20260622071935_llm_calls
-- Generated by bin/new-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.
-- See docs/adr-migration-timestamps.md.

CREATE TABLE llm_calls (
    id         TEXT    PRIMARY KEY,
    stage      TEXT    NOT NULL CHECK (stage IN ('extract', 'compile', 'ask')),
    job_id     TEXT    NOT NULL DEFAULT '',
    attempt    INTEGER NOT NULL CHECK (attempt >= 1),
    provider   TEXT    NOT NULL,
    model      TEXT    NOT NULL,
    params     TEXT    NOT NULL DEFAULT '',
    request    TEXT    NOT NULL DEFAULT '',
    response   TEXT    NOT NULL DEFAULT '',
    usage      TEXT    NOT NULL DEFAULT '',
    err        TEXT    NOT NULL DEFAULT '',
    started_at TEXT    NOT NULL,
    ended_at   TEXT    NOT NULL
);

CREATE INDEX llm_calls_job_stage ON llm_calls (job_id, stage, attempt);
CREATE INDEX llm_calls_started_at ON llm_calls (started_at, id);

-- TODO: write the forward-only schema change below.
