-- migration: 20260625015005_page_embeddings
-- Generated by bin/new-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.
-- See docs/adr-migration-timestamps.md.

CREATE TABLE page_embeddings (
    subject_id   TEXT    PRIMARY KEY,
    model        TEXT    NOT NULL,
    dims         INTEGER NOT NULL CHECK (dims >= 0),
    vec          BLOB    NOT NULL CHECK (length(vec) = dims * 4),
    content_hash TEXT    NOT NULL,
    updated_at   INTEGER NOT NULL
);
