-- migration: 20260625020905_create_pages_fts
-- Generated by bin/new-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.
-- See docs/adr-migration-timestamps.md.

CREATE VIRTUAL TABLE pages_fts USING fts5(
    title,
    body,
    content='pages',
    content_rowid='rowid'
);

INSERT INTO pages_fts(pages_fts) VALUES('rebuild');
