-- migration: 20260624200122_widen_llm_calls_stage
-- Generated by bin/new-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.
-- See docs/adr-migration-timestamps.md.

CREATE TABLE llm_calls_rebuild (
    id         TEXT    PRIMARY KEY,
    job_id     TEXT    NOT NULL DEFAULT '',
    stage      TEXT    NOT NULL CHECK (stage IN ('extract', 'compile', 'ask-subject', 'ask-synthesis', 'judge')),
    attempt    INTEGER NOT NULL DEFAULT 1,
    provider   TEXT    NOT NULL DEFAULT '',
    model      TEXT    NOT NULL DEFAULT '',
    params     TEXT    NOT NULL DEFAULT '{}',
    request    TEXT    NOT NULL DEFAULT '',
    response   TEXT    NOT NULL DEFAULT '',
    usage      TEXT    NOT NULL DEFAULT '',
    err        TEXT    NOT NULL DEFAULT '',
    started_at TEXT    NOT NULL DEFAULT '',
    ended_at   TEXT    NOT NULL DEFAULT ''
);

INSERT INTO llm_calls_rebuild (
    id, job_id, stage, attempt, provider, model, params, request,
    response, usage, err, started_at, ended_at
)
SELECT
    id, job_id, stage, attempt, provider, model, params, request,
    response, usage, err, started_at, ended_at
FROM llm_calls;

DROP TABLE llm_calls;
ALTER TABLE llm_calls_rebuild RENAME TO llm_calls;

CREATE INDEX llm_calls_job ON llm_calls (job_id, started_at, id);
CREATE INDEX llm_calls_time ON llm_calls (started_at, id);
