// Package optctl is the on-box platform CLI's core: the install / rollback /
// prune verbs over the versioned release-dir + atomic-symlink layout (PLAN §1.4,
// ADR "optctl — per-verb internals").
//
// EVERY filesystem operation is rooted at a configurable base (OPTCTL_ROOT,
// default /opt) so the whole package is testable against a temp dir with no real
// box. The box-only bits — systemd restart / is-active, and subprocess
// invocation of the app binary's fixed verbs (version|manifest|migrate|schema|
// backup|restore) — sit behind the System and AppRunner seams the tests stub.
package optctl

import (
	"path/filepath"
)

// Layout resolves the on-box paths for one app under a configurable root. The
// real box uses root="/opt"; tests use a temp dir. The stable paths bin/run and
// etc/manifest.env (PLAN §2.6) and the never-touched data/<app>.db (PLAN §2.7)
// are computed here so every verb shares one definition.
type Layout struct {
	Root string // OPTCTL_ROOT, default "/opt"
	App  string // service name
}

// NewLayout builds the layout for app under root (root="" ⇒ "/opt").
func NewLayout(root, app string) Layout {
	if root == "" {
		root = "/opt"
	}
	return Layout{Root: root, App: app}
}

// AppDir is /opt/<app> — the per-app install root.
func (l Layout) AppDir() string { return filepath.Join(l.Root, l.App) }

// ReleasesDir is /opt/<app>/releases — the parent of every versioned release.
func (l Layout) ReleasesDir() string { return filepath.Join(l.AppDir(), "releases") }

// ReleaseDir is /opt/<app>/releases/<version> — one version's directory.
func (l Layout) ReleaseDir(version string) string {
	return filepath.Join(l.ReleasesDir(), version)
}

// ReleaseBinary is /opt/<app>/releases/<version>/<app> — the binary for a version.
func (l Layout) ReleaseBinary(version string) string {
	return filepath.Join(l.ReleaseDir(version), l.App)
}

// CurrentLink is /opt/<app>/current — the symlink swapped atomically to point at
// the live release dir (ln -sfn semantics).
func (l Layout) CurrentLink() string { return filepath.Join(l.AppDir(), "current") }

// CurrentBinary is /opt/<app>/current/<app> — the binary reached through current.
func (l Layout) CurrentBinary() string { return filepath.Join(l.CurrentLink(), l.App) }

// BinDir is /opt/<app>/bin.
func (l Layout) BinDir() string { return filepath.Join(l.AppDir(), "bin") }

// RunLink is /opt/<app>/bin/run — the STABLE path metaspot-launch execs. A
// symlink to ../current/<app>; set once and never repointed (the cutover happens
// at CurrentLink), so it stays valid mid-swap (PLAN §2.6).
func (l Layout) RunLink() string { return filepath.Join(l.BinDir(), "run") }

// RunTarget is the relative target bin/run points at: ../current/<app>. Relative
// so the symlink survives a box-path move and resolves through CurrentLink.
func (l Layout) RunTarget() string {
	return filepath.Join("..", "current", l.App)
}

// EtcDir is /opt/<app>/etc.
func (l Layout) EtcDir() string { return filepath.Join(l.AppDir(), "etc") }

// ManifestPath is /opt/<app>/etc/manifest.env — the STABLE path the dashboard's
// resource derivation and bin/registry read; regenerated by `<app> manifest` on
// every swap (PLAN §2.6).
func (l Layout) ManifestPath() string { return filepath.Join(l.EtcDir(), "manifest.env") }

// DataDir is /opt/<app>/data.
func (l Layout) DataDir() string { return filepath.Join(l.AppDir(), "data") }

// DBPath is /opt/<app>/data/<app>.db — state, NEVER touched on deploy except the
// explicit pre-migration backup copy (PLAN §2.7).
func (l Layout) DBPath() string { return filepath.Join(l.DataDir(), l.App+".db") }

// GenerationPath is the event-plane epoch sidecar next to the DB.
func (l Layout) GenerationPath() string { return l.DBPath() + ".generation" }

// BackupsDir is /opt/<app>/backups — where install drops the pre-migration DB
// snapshot keyed by the FROM-version, so the matching rollback can restore it.
func (l Layout) BackupsDir() string { return filepath.Join(l.AppDir(), "backups") }

// PreMigrationBackup is the snapshot install takes before a schema-advancing
// migrate, named by the version being installed (the rollback target restores the
// snapshot whose name matches the release it is rolling back FROM).
func (l Layout) PreMigrationBackup(version string) string {
	return filepath.Join(l.BackupsDir(), "pre-"+version+".db")
}
